### ISSUE TITLE
知乎反爬

### ISSUE THREAD

**Issue by myunxi** [brianway/webporter#9]
现在知乎已经加上反爬的功能了，如何破解，我每次爬一会就把账号给冻结了

**Comment by brianway** [comment]
我写这个项目的初衷是展示如何使用爬虫框架进行实战，提供一个样例。至于反爬之类的，目前不提供解决方案。

最简单的做法是，在 config.json 里，把每次访问的延时设置长点，现在默认的是 500 ms，线程 20 个，如果还不行，就再降低频率，模拟人工点击的频率，应该是不会被封的。

**Comment by Dtrycode** [comment]
请问下面这个exception是什么情况呀？是代码哪里需要修改吗？我已经把configuration的内容按要求改过了。
17-06-16 09:38:32,504 INFO  
us.codecraft.webmagic.downloader.HttpClientDownloader(HttpClientDownloader.java:88) ## downloading page https://www.zhihu.com/api/v4/members/qeuiozxcnm/followees?include=data%5B*%5D.url_token&offset=0&per_page=30&limit=30
17-06-16 09:38:32,535 WARN  us.codecraft.webmagic.downloader.HttpClientDownloader(HttpClientDownloader.java:114) ## download page https://www.zhihu.com/api/v4/members/faith_gmb/followees?include=data%5B*%5D.url_token&offset=0&per_page=30&limit=30 error
org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at us.codecraft.webmagic.downloader.HttpClientDownloader.download(HttpClientDownloader.java:102)
	at us.codecraft.webmagic.Spider.processRequest(Spider.java:404)
	at us.codecraft.webmagic.Spider$1.run(Spider.java:321)
	at us.codecraft.webmagic.thread.CountableThreadPool$1.run(CountableThreadPool.java:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.http.ProtocolException: Invalid redirect URI: /account/unhuman?type=imfrozen&æ¨å¥½ï¼æ¨çå¸å·è¢«ç³»ç»æ£æµå°å­å¨å¼å¸¸æµéï¼å·²ææ¶è¢«éå¶ä½¿ç¨ï¼å¦æçé®ï¼æ¨å¯ä»¥åéé®ä»¶è³ antispam@zhihu.com èç³»æä»¬ã
	at org.apache.http.impl.client.DefaultRedirectStrategy.createLocationURI(DefaultRedirectStrategy.java:199)
	at org.apache.http.impl.client.DefaultRedirectStrategy.getLocationURI(DefaultRedirectStrategy.java:147)
	at us.codecraft.webmagic.downloader.CustomRedirectStrategy.getRedirect(CustomRedirectStrategy.java:28)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:121)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	... 9 more
Caused by: java.net.URISyntaxException: Illegal character in query at index 32: /account/unhuman?type=imfrozen&æ¨å¥½ï¼æ¨çå¸å·è¢«ç³»ç»æ£æµå°å­å¨å¼å¸¸æµéï¼å·²ææ¶è¢«éå¶ä½¿ç¨ï¼å¦æçé®ï¼æ¨å¯ä»¥åéé®ä»¶è³ antispam@zhihu.com èç³»æä»¬ã
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3111)
	at java.net.URI$Parser.parse(URI.java:3063)
	at java.net.URI.<init>(URI.java:588)
	at org.apache.http.impl.client.DefaultRedirectStrategy.createLocationURI(DefaultRedirectStrategy.java:188)
	... 13 more
